[ch2]
expected = [
    "[kernel] PageFault in application, kernel killed it.",
    
    "Hello from C!",
    
    "Hello, world from user mode program!",
    
    "3^200000 = 871008973(MOD 998244353)",
    'r"Test power_3 OK\d+!"',
    
    "Testing open/read/close...",
    'r"sys_open: path = test_file\d+"',
    "Read content: Success!",
    'r"sys_close: fd = \d+"',
]
not_expected = ["FAIL: T.T"]

[ch3]
expected = [
    'r"Test write A OK\d+!"',
    'r"Test write B OK\d+!"',
    'r"Test write C OK\d+!"',

    'r"Success\d+ trace_simple!"',

    'r"SYSCALL_WRITE count completed\d+ after writes: \d+"',
    'r"Task Status: \d+ \(RUNNING\) OK\d+!"',
    'r"Success\d+! Total syscalls: \d+"',
    'r"Success\d+! Total syscalls made: \d+"',
]
not_expected = ["FAIL: T.T"]

[ch4]
inherit_from = "ch3"
expected = [
    "Test sbrk almost OK!",
]
not_expected = ["Test sbrk failed!"]

[ch5]
inherit_from = "ch4"
expected = [
    "Test spawn0 OK!",
    "Test wait OK!",
    "Test waitpid OK!",
    "Test set_priority OK!",
]
exclude = [
    "string from task trace test",
    "Test trace OK!",
    "Test trace_1 OK!",
]
not_expected = []



