[ch2]
expected = [
    "[kernel] PageFault in application, kernel killed it.",
    
    "Hello from C!",
    
    "Hello, world from user mode program!",
    
    "3^200000 = 871008973(MOD 998244353)",
    'r"Test power_3 OK\d+!"',
    
    "Testing open/read/close...",
    "sys_open: path = test_file",
    'r"Read content: Success\d+!"',
    'r"sys_close: fd = \d+"',
    
    'r"All applications completed\d+!"',
]
not_expected = ["FAIL: T.T"]

[ch3]
expected = [
    "Test write A OK!",
    "Test write B OK!",
    "Test write C OK!",
    'r"get_time OK! (\d+)"',
    "Test sleep OK!",
    'r"current time_msec = (\d+)"',
    'r"time_msec = (\d+) after sleeping (\d+) ticks, delta = (\d+)ms!"',
    "Test sleep1 passed!",
    "string from task trace test",
    "Test trace OK!",
]
not_expected = ["FAIL: T.T"]

[ch4]
inherit_from = "ch3"
expected = [
    "Test sbrk almost OK!",
]
not_expected = ["Test sbrk failed!"]

[ch5]
inherit_from = "ch4"
expected = [
    "Test spawn0 OK!",
    "Test wait OK!",
    "Test waitpid OK!",
    "Test set_priority OK!",
]
exclude = [
    "string from task trace test",
    "Test trace OK!",
    "Test trace_1 OK!",
]
not_expected = []



